name: cryptography_utils
description: "Cryptography utils"
version: 0.0.13

environment:
  sdk: ">=3.1.4"

dependencies:
  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  # https://pub.dev/packages/equatable
  equatable: 2.0.5

  # Implementations of SHA, MD5, and HMAC cryptographic functions.
  # https://pub.dev/packages/crypto
  crypto: 3.0.3

  # Library implementing Bitcoins BIP173 (Bech32 encoding) specification in a Flutter friendly fashion.
  # https://pub.dev/packages/bech32
  bech32: 0.2.2

  # A Dart library implementing cryptographic algorithms and primitives, modeled on the BouncyCastle library.
  # https://pub.dev/packages/pointycastle
  pointycastle: 3.7.4

  # Flutter's compute function made available for all non-Flutter Dart programs
  # https://pub.dev/packages/compute
  compute: 1.0.2

  # The decimal package allows you to deal with decimal numbers without losing precision.
  # https://pub.dev/packages/decimal
  decimal: 2.3.3

dev_dependencies:
  test: 1.25.5
