name: cryptography_utils
description: "Dart package containing utility methods for common cryptographic and blockchain-specific operations"
publish_to: none
version: 0.0.18

environment:
  sdk: ">=3.2.6"

dependencies:
  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  # https://pub.dev/packages/equatable
  equatable: 2.0.5

  # Implementations of SHA, MD5, and HMAC cryptographic functions.
  # https://pub.dev/packages/crypto
  crypto: 3.0.3

  # A Dart library implementing cryptographic algorithms and primitives, modeled on the BouncyCastle library.
  # https://pub.dev/packages/pointycastle
  pointycastle: 3.9.1

  # Flutter's compute function made available for all non-Flutter Dart programs
  # https://pub.dev/packages/compute
  compute: 1.0.2

  # The decimal package allows you to deal with decimal numbers without losing precision.
  # https://pub.dev/packages/decimal
  decimal: 2.3.3

  # Dart package containing utility methods for data encoding and decoding.
  codec_utils:
    git:
      url: https://github.com/snggle/codec_utils.git
      ref: master

dev_dependencies:
  # A full featured library for writing and running Dart tests across platforms.
  # https://pub.dev/packages/test
  test: 1.25.5
