// This class was primarily influenced by:
// "pointycastle" - Copyright (c) 2000 - 2019 The Legion of the Bouncy Castle Inc. (https://www.bouncycastle.org)
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
// of the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
// FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
// COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
// IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

import 'dart:typed_data';

import 'package:cryptography_utils/src/encryption/cipher/a_block_cipher.dart';
import 'package:cryptography_utils/src/encryption/cipher/i_cipher_param.dart';
import 'package:cryptography_utils/src/encryption/cipher/param_with_iv.dart';
import 'package:cryptography_utils/src/utils/binary_utils.dart';

/// A simplified implementation of a stream cipher in SIC (also known as CTR) mode,
/// using AES as the underlying block cipher.
class SicStreamAsBlockCipher extends ABlockCipher {
  ABlockCipher blockCipher;
  late Uint8List _ivUint8List;
  late Uint8List _counterUint8List;
  late Uint8List _counterOutUint8List;
  late int _consumed;

  /// Initializes buffers based on AES block size.
  SicStreamAsBlockCipher(this.blockCipher) : super(blockCipher.blockSize) {
    _ivUint8List = Uint8List(blockCipher.blockSize);
    _counterUint8List = Uint8List(blockCipher.blockSize);
    _counterOutUint8List = Uint8List(blockCipher.blockSize);
  }

  /// Initializes the cipher with the IV and key.
  /// Only encryption mode is used internally as SIC is symmetric for both operations.
  @override
  void init(ICipherParam? cipherParam) {
    ParamWithIV<ICipherParam?> parameterWithIV = cipherParam as ParamWithIV<ICipherParam?>;
    _ivUint8List.setAll(0, parameterWithIV.ivUint8List);
    _reset();
    blockCipher.init(parameterWithIV.param);
  }

  /// Processes the input [uint8list] by XOR'ing with encrypted counter blocks
  /// generated by the underlying block cipher in SIC (counter) mode.
  /// This method can handle input of any length and returns the processed
  /// (encrypted or decrypted) output as a [Uint8List].
  @override
  Uint8List process(Uint8List uint8list) {
    Uint8List outputUint8List = Uint8List(uint8list.length);
    _processBytes(uint8list, 0, uint8list.length, outputUint8List, 0);
    return outputUint8List;
  }

  /// Processes a single block of input data starting at [inputOffset] and writes
  /// the result to [outputUint8List] starting at [outputOffset].
  /// Internally uses [_processBytes] to perform a block-sized XOR operation
  /// using the stream cipher's counter mode logic.
  /// Returns the number of bytes processed, which is always equal to [blockSize].
  @override
  int processBlock(Uint8List inputUint8List, int inputOffset, Uint8List outputUint8List, int outputOffset) {
    _processBytes(inputUint8List, inputOffset, blockSize, outputUint8List, outputOffset);
    return blockSize;
  }

  /// Processes a slice of input and outputs the XOR'd result to [outputUint8List].
  void _processBytes(Uint8List inputUint8List, int inputOffset, int length, Uint8List outputUint8List, int outOffset) {
    for (int i = 0; i < length; i++) {
      outputUint8List[outOffset + i] = _returnByte(inputUint8List[inputOffset + i]);
    }
  }

  /// XORs a single byte with a byte from the encrypted counter.
  /// Automatically re-feeds the counter when exhausted.
  int _returnByte(int input) {
    if (_consumed >= _counterOutUint8List.length) {
      blockCipher.processBlock(_counterUint8List, 0, _counterOutUint8List, 0);
      _incrementCounter();
      _consumed = 0;
    }
    return BinaryUtils.maskTo8Bits(input) ^ _counterOutUint8List[_consumed++];
  }

  /// Resets the engine and counters to the initial IV.
  void _reset() {
    _counterUint8List.setAll(0, _ivUint8List);
    _counterOutUint8List.fillRange(0, _counterOutUint8List.length, 0);
    _consumed = _counterOutUint8List.length;
  }

  /// Increments the counter value (big endian-style).
  void _incrementCounter() {
    for (int i = _counterUint8List.length - 1; i >= 0; i--) {
      _counterUint8List[i]++;
      if (_counterUint8List[i] != 0) {
        break;
      }
    }
  }
}
