enum SolanaInstructionType {
  systemTransfer,
  tokenTransfer,
  computeBudgetUnitPrice,
  computeBudgetUnitLimit,
  invalidInstruction,
  systemCreateAccount,
  systemAssign,
  stakeInitialize,
  stakeDelegate,
  stakeDeactivate,
  stakeWithdraw,
  swap,
  swapJupiter,
  unknown,
}