import 'dart:convert';
import 'dart:typed_data';

import 'package:cryptography_utils/cryptography_utils.dart';
import 'package:cryptography_utils/src/encryption/aes/aes.dart';
import 'package:cryptography_utils/src/encryption/aes/aes_iv.dart';
import 'package:cryptography_utils/src/encryption/aes/aes_key.dart';
import 'package:cryptography_utils/src/encryption/aes/encrypted.dart';
import 'package:cryptography_utils/src/utils/secure_random.dart';

/// Provides AES-256 encryption and decryption using a password-based key derivation scheme.
/// This implementation follows a simplified Diffie-Hellman key exchange pattern,
/// where a secure derived key is generated by hashing the password and a random salt.
/// The key is then used to perform AES encryption in stream mode with PKCS7 padding.
class Aes256DHKE {
  /// Encrypts the provided plaintext using the given password.
  /// A random salt is generated and combined with the password to derive the encryption key
  /// and IV. The plaintext is then encrypted and returned as a Base64-encoded string
  /// with the salt and a checksum appended.
  static String encrypt(String password, String decryptedString) {
    Uint8List decryptedUint8List = utf8.encode(decryptedString);
    Uint8List randomUint8List = SecureRandom.getBytes(length: 16, max: 255);

    Uint8List hashedPasswordUint8List = Sha256().convert(utf8.encode(password)).byteList;
    Uint8List securePasswordBytesList = Sha256().convert(randomUint8List + hashedPasswordUint8List).byteList;

    AesKey aesKey = AesKey(hashedPasswordUint8List);

    Uint8List initializationVectorUint8List = Uint8List.fromList(securePasswordBytesList.getRange(0, 16).toList());
    AesIV aesIV = AesIV(initializationVectorUint8List);

    Uint8List encryptedUint8List = AES.encryptBytes(decryptedUint8List, aesKey, aesIV).uint8List;

    List<int> checksumBytesList = securePasswordBytesList.getRange(securePasswordBytesList.length - 4, securePasswordBytesList.length).toList();
    List<int> encryptedStringBytesList = randomUint8List + encryptedUint8List + checksumBytesList;
    String encryptedString = base64Encode(encryptedStringBytesList);

    return encryptedString;
  }

  /// Decrypts the provided encrypted Base64 string using the specified password.
  ///
  /// The salt and checksum are extracted from the encrypted string, and the key
  /// and IV are reconstructed using the same derivation method. The decrypted
  /// plaintext is returned as a UTF-8 string.
  static String decrypt(String password, String encryptedString) {
    Uint8List hashedPasswordUint8List = Sha256().convert(utf8.encode(password)).byteList;

    Uint8List encryptedStringUint8List = base64Decode(encryptedString);
    Uint8List randomUint8List = Uint8List.fromList(encryptedStringUint8List.getRange(0, 16).toList());
    Encrypted cipherText = Encrypted(Uint8List.fromList(encryptedStringUint8List.getRange(16, encryptedStringUint8List.length - 4).toList()));
    Uint8List securePasswordUint8List = Sha256().convert(randomUint8List + hashedPasswordUint8List).byteList;

    AesKey aesKey = AesKey(hashedPasswordUint8List);

    Uint8List initializationVectorUint8List = Uint8List.fromList(securePasswordUint8List.getRange(0, 16).toList());
    AesIV aesIV = AesIV(initializationVectorUint8List);
    Uint8List decryptedUint8List = AES.decryptBytes(cipherText, aesKey, aesIV);
    String decryptedString = utf8.decode(decryptedUint8List);
    return decryptedString;
  }

  /// Validates whether the provided [password] matches the checksum of the [encryptedString].
  /// This function checks if the password-derived checksum matches the stored one in the encrypted payload,
  /// without actually decrypting the content.
  /// Returns `true` if the password is valid; otherwise `false`.
  static bool isPasswordValid(String password, String encryptedString) {
    Uint8List hashedPasswordUint8List = Sha256().convert(utf8.encode(password)).byteList;

    Uint8List encryptedStringUint8List = base64Decode(encryptedString);
    Uint8List randomUint8List = Uint8List.fromList(encryptedStringUint8List.getRange(0, 16).toList());
    List<int> expectedChecksumBytesList =
        encryptedStringUint8List.getRange(encryptedStringUint8List.length - 4, encryptedStringUint8List.length).toList();

    Uint8List securePasswordUint8List = Sha256().convert(randomUint8List + hashedPasswordUint8List).byteList;
    List<int> actualChecksumBytesList = securePasswordUint8List.getRange(securePasswordUint8List.length - 4, securePasswordUint8List.length).toList();

    return actualChecksumBytesList.toString() == expectedChecksumBytesList.toString();
  }
}
