import 'dart:typed_data';

import 'package:cryptography_utils/src/encryption/cipher/block_cipher/a_block_cipher.dart';
import 'package:cryptography_utils/src/encryption/cipher/stream_cipher/ctr_stream_cipher.dart';

class CTRBlockCipher extends ABlockCipher {
  final CTRStreamCipher streamCipher;

  CTRBlockCipher(ABlockCipher blockCipher)
      : streamCipher = CTRStreamCipher(blockCipher),
        super(
        blockSize: blockCipher.blockSize,
        cipherMode: blockCipher.cipherMode,
        cipherParameter: blockCipher.cipherParameter,
      );

  /// Processes the input [uint8list] by XOR'ing with encrypted counter blocks
  /// generated by the underlying block cipher in SIC (counter) mode.
  /// This method can handle input of any length and returns the processed
  /// (encrypted or decrypted) output as a [Uint8List].
  @override
  Uint8List process(Uint8List uint8list) {
    Uint8List outputUint8List = Uint8List(uint8list.length);
    streamCipher.processBytes(uint8list, 0, outputUint8List, 0);
    return outputUint8List;
  }

  /// Processes a single block of input data starting at [inputOffset] and writes
  /// the result to [outputUint8List] starting at [outputOffset].
  /// Internally uses [_processBytes] to perform a block-sized XOR operation
  /// using the stream cipher's counter mode logic.
  /// Returns the number of bytes processed, which is always equal to [blockSize].
  @override
  int processBlock(Uint8List inputUint8List, int inputOffset, Uint8List outputUint8List, int outputOffset) {
    streamCipher.processBytes(inputUint8List, inputOffset, outputUint8List, outputOffset);
    return blockSize;
  }
}